[package]
name = "pcg_rand"
version = "0.2.0"
authors = ["Jeb Brooks <robojeb@robojeb.xyz>"]

[lib]
name = "pcg_rand"
path = "src/lib.rs"

[[bin]]
name = "pcg_demo"
path = "src/main.rs"

[dependencies]

rand = "0.3.11"
