[package]
name = "pcg_rand"
version = "0.7.0"
authors = ["Jeb Brooks <robojeb@robojeb.xyz>"]

homepage = "https://github.com/robojeb/pcg_rand"
repository = "https://github.com/robojeb/pcg_rand"
documentation = "https://robojeb.xyz/doc/pcg_rand"

license = "Apache-2.0"

keywords = ["rand", "pcg"]

readme = "README.md"

description = "An implementation of the PCG family of random number generators in pure Rust"

[lib]
name = "pcg_rand"
path = "src/lib.rs"

[[bin]]
name = "pcg_demo"
path = "src/main.rs"

[dependencies]
rand = "0.3.13"
num-traits = "0.1.32"

[dependencies.extprim]
version = "1.0.0"
optional = true

[features]
#By default use extprim feature
default = ["extprim_u128"]

extprim_u128 = ["extprim"]
